SNOWFLAKE_DBT_T20:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: NSZFGKQ-KM67393
      user: RAUNITRAJ161021
      password: R@unitr@j@1234$
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: RAUNIT_T20_DBT
      schema: T20_DATA_TRANSFORM

    ci:
      type: snowflake
      account: NSZFGKQ-KM67393
      user: RAUNITRAJ161021
      password: R@unitr@j@1234$
      role: ACCOUNTADMIN
      database: RAUNIT_T20_DBT
      warehouse: COMPUTE_WH
      schema: T20_DATA_TRANSFORM
      threads: 4
      client_session_keep_alive: False