version: 2
models:
  - name: STG_RAW_PLAYER
    description: ""
    constraints:
      - type: primary_key
        columns: playerid
    columns:
      - name: playerid
        data_type: number
        description: ""
      - name: playername
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
        # tests:
        #   - unique
      - name: filename
        data_type: varchar
        description: ""
        constraints: 
          - type: not_null
      - name: load_timestamp
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
      - name: _inserted_at_
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null

  - name: STG_RAW_PLAYER2
    description: ""
    constraints:
      - type: primary_key
        columns: playerid
    columns:
      - name: playerid
        data_type: number
        description: ""
      - name: playername
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: filename
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: load_timestamp
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
      - name: _inserted_at_
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null

  - name: STG_RAW_PLAYER3
    description: ""
    constraints:
      - type: primary_key
        columns: playerid
    columns:
      - name: playerid
        data_type: number
        description: ""
      - name: playername
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: filename
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: load_timestamp
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
      - name: _inserted_at_
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
  
  - name: STG_RAW_PLAYER4
    description: ""
    constraints:
      - type: primary_key
        columns: playerid
    columns:
      - name: playerid
        data_type: number
        description: ""
      - name: playername
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: filename
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: load_timestamp
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
      - name: _inserted_at_
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null

  - name: STG_RAW_PLAYER5
    description: ""
    constraints:
      - type: primary_key
        columns: playerid
    columns:
      - name: playerid
        data_type: number
        description: ""
      - name: playername
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: filename
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: load_timestamp
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
      - name: _inserted_at_
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null

  - name: STG_RAW_PLAYER6
    description: ""
    constraints:
      - type: primary_key
        columns: playerid
    columns:
      - name: playerid
        data_type: number
        description: ""
      - name: playername
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: filename
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: load_timestamp
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
      - name: _inserted_at_
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null

  - name: STG_RAW_PLAYERSEASON
    description: ""
    constraints:
      - type: primary_key
        columns: [playerid, teamid]
    columns:
      - name: playerid
        data_type: number
        description: ""
      - name: teamid
        data_type: number
        description: ""
      - name: season
        data_type: number
        description: ""
        constraints:
          - type: not_null
      - name: filename
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: load_timestamp
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
      - name: _inserted_at_
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null

  - name: STG_RAW_BATTINGCARD
    description: ""
    constraints:
      - type: primary_key
        columns: [matchid, batsmanid]
    columns:
      - name: matchid
        data_type: number
        description: ""
      - name: inningid
        data_type: number
        description: ""
        constraints:
          - type: not_null
      - name: playorder
        data_type: number
        description: ""
        constraints:
          - type: not_null
      - name: batsmanid
        data_type: number
        description: ""
      - name: dismissaltypeid
        data_type: number
        description: ""
      - name: bowlerid
        data_type: number
        description: ""
      - name: fielderid
        data_type: number
        description: ""
      - name: runs
        data_type: number
        description: ""
      - name: balls
        data_type: number
        description: ""
      - name: bounderies
        data_type: number
        description: ""
      - name: sixes
        data_type: number
        description: ""
      - name: dotsballs
        data_type: number
        description: ""
      - name: filename
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: load_timestamp
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
      - name: _inserted_at_
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null

  - name: STG_RAW_BOWLINGCARD
    description: ""
    constraints:
      - type: primary_key
        columns: [matchid, bowlerid]
    columns:
      - name: matchid
        data_type: number
        description: ""
      - name: inningid
        data_type: number
        description: ""
        constraints:
          - type: not_null
      - name: bowlerid
        data_type: number
        description: ""
      - name: ballsbowled
        data_type: number
        description: ""
      - name: maidens
        data_type: number
        description: ""
      - name: dotballs
        data_type: number
        description: ""
      - name: runsgiven
        data_type: number
        description: ""
      - name: bounderiesconceded
        data_type: number
        description: ""
      - name: sixesconceded
        data_type: number
        description: ""
      - name: noballs
        data_type: number
        description: ""
      - name: wides
        data_type: number
        description: ""
      - name: wicketstaken
        data_type: number
        description: ""
      - name: filename
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: load_timestamp
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
      - name: _inserted_at_
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null

  - name: STG_RAW_TEAM
    description: ""
    constraints:
      - type: primary_key
        columns: teamid
    columns:
      - name: teamid
        data_type: number
        description: ""
      - name: teamname
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: filename
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: load_timestamp
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
      - name: _inserted_at_
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null

  - name: STG_RAW_TEAM2
    description: ""
    constraints:
      - type: primary_key
        columns: teamid
    columns:
      - name: teamid
        data_type: number
        description: ""
      - name: teamname
        data_type: varchar
        description: ""
      - name: filename
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: load_timestamp
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
      - name: _inserted_at_
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
  
  - name: STG_RAW_TEAM3
    description: ""
    constraints:
      - type: primary_key
        columns: teamid
    columns:
      - name: teamid
        data_type: number
        description: ""
      - name: teamname
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: filename
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: load_timestamp
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
      - name: _inserted_at_
        data_type: timestamp_ntz
        description: ""
  
  - name: STG_RAW_TEAM4
    description: ""
    constraints:
      - type: primary_key
        columns: teamid
    columns:
      - name: teamid
        data_type: number
        description: ""
      - name: teamname
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: filename
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: load_timestamp
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
      - name: _inserted_at_
        data_type: timestamp_ntz
        description: ""

  - name: STG_RAW_TEAM5
    description: ""
    constraints:
      - type: primary_key
        columns: teamid
    columns:
      - name: teamid
        data_type: number
        description: ""
      - name: teamname
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: filename
        data_type: varchar
        description: ""
        constraints:
          - type: not_null
      - name: load_timestamp
        data_type: timestamp_ntz
        description: ""
        constraints:
          - type: not_null
      - name: _inserted_at_
        data_type: timestamp_ntz
        description: ""
